# Generated by Django 5.0.6 on 2024-10-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_category_alter_blogpost_author_blogpost_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
    ]
