# Generated by Django 5.0.6 on 2024-10-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_like_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
