# Generated by Django 5.0.6 on 2024-10-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blogpost'),
        ),
    ]
